config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /en|ru/ do
    root :to => 'home#index'

    get 'signin' => 'user_sessions#new', :as => :signin
    post 'signin' => 'user_sessions#create'
    match 'signout' => 'user_sessions#destroy', :as => :signout, via: [:get, :post]

    match 'login' => 'distillator#login', :as => :login, via: [:get, :post]
    match 'get_all_user' => 'distillator#get_all_user', :as => :get_all_user, via: [:get, :post]
    match 'set_parameters' => 'distillator#set_parameters', :as => :set_parameters, via: [:get, :post]
    match 'get_parameters' => 'distillator#get_parameters', :as => :get_parameters, via: [:get, :post]
    match 'get_user_in_radius' => 'distillator#get_user_in_radius', :as => :get_user_in_radius, via: [:get, :post]


    get 'signup' => 'users#new', :as => :signup
    post 'signup' => 'users#create'
  end
  get "/" => "home#index"
end

app/views/templates/_application_header.html.erb
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <%= image_tag("header/profile.png", class: "img-responsive", title: "") %>
                <div class="intro-text">
                    <span class="name"><%= t('distillator') %></span>
                    <hr class="star-light">
                    <span class="skills">Web Developer - Graphic Artist - User Experience Designer</span>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/templates/_application_main_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to t('distillator'), root_url, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                    <li><%= link_to(signout_url) do %>
                            <%= t('navigation.application.mainmenu.signout') %>
                            <span class="glyphicon glyphicon-log-out"></span>
                        <% end %></li>
                <% else %>
                    <li><%= link_to(signin_url) do %>
                            <%= t('navigation.application.mainmenu.signin') %>
                            <span class="glyphicon glyphicon-user"></span>
                        <% end %></li>
                    <li><%= link_to(signup_url) do %>
                            <%= t('navigation.application.mainmenu.signup') %>
                            <span class="glyphicon glyphicon-log-in"></span>
                        <% end %></li>
                <% end %>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <%= @current_language.name %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <li><%= link_to t('navigation.application.mainmenu.english'), make_url_for_en %></li>
                        <li><%= link_to t('navigation.application.mainmenu.russian'), make_url_for_ru %></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/templates/_main_footer.html.erb
<div id="footer-box">
  <div id="navigation-shortcuts" class="container">
      <ul class="shortcut col-md-2 col-sm-6 col-xs-12">

      </ul>
      <ul class="shortcut col-md-2 col-sm-6 col-xs-12">

      </ul>
      <ul class="shortcut col-md-2 col-sm-6 col-xs-12">

      </ul>
      <ul class="shortcut col-md-2 col-sm-6 col-xs-12">

      </ul>
      <ul class="shortcut col-md-4 col-sm-12 col-xs-12 social-networks">
          <li class="row">
              <% if I18n.locale == :en %>
                  <div class="col-md-4 col-sm-4 col-xs-4"><%= link_to_social_network("facebook", "https://www.facebook.com") %></div>
                  <div class="col-md-4 col-sm-4 col-xs-4"><%= link_to_social_network("googleplus", "https://plus.google.com") %></div>
                  <div class="col-md-4 col-sm-4 col-xs-4"><%= link_to_social_network("linkedin", "https://www.linkedin.com") %></div>
              <% elsif I18n.locale == :ru %>
                  <div class="col-md-4 col-sm-4 col-xs-4"><%= link_to_social_network("facebook", "https://www.facebook.com") %></div>
                  <div class="col-md-4 col-sm-4 col-xs-4"><%= link_to_social_network("googleplus", "https://plus.google.com") %></div>
                  <div class="col-md-4 col-sm-4 col-xs-4"><%= link_to_social_network("vkontakte", "https://vk.com") %></div>
              <% end %>
          </li>
      </ul>
  </div>
  <div class="clear"></div>
  <div id="legacy-notes">
    <div class="copyright">&copy; <%= t("footer.copyright") %>.</div>
  </div>
</div>

app/views/templates/_system_flash.html.erb
<% if has_flash_any_key_with_message? %>
  <div id="system-flash" class="container">
    <% if flash.key?(:notice) %>
      <div class="notice row">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>
    <% if flash.key?(:information) %>
      <div class="information row">
        <p><%= flash[:information] %></p>
      </div>
    <% end %>
    <% if flash.key?(:warning) %>
      <div class="warning row">
        <p><%= flash[:warning] %></p>
      </div>
    <% end %>
    <% if flash.key?(:error) %>
      <div class="error row">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </div>
<% end %>